# Generated by Django 3.2 on 2022-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='start_price',
            field=models.CharField(max_length=50),
        ),
    ]
