# Generated by Django 3.2 on 2022-08-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_food_start_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='card_number',
            field=models.CharField(max_length=50),
        ),
    ]
